//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompetitiveRankingWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.Playthroughs = new HashSet<Playthrough>();
        }
    
        public int GameID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Publisher_ID { get; set; }
        public Nullable<int> Developer_ID { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public int Rating { get; set; }
        public int CompetedIn { get; set; }
    
        public virtual Developer Developer { get; set; }
        public virtual Publisher Publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Playthrough> Playthroughs { get; set; }
    }
}
